spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    url: jdbc:h2:mem:auth-us;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    password:
    username: sa
    driverClassName: org.h2.Driver
  rsocket:
    server:
      transport: websocket
      mapping-path: /rsocket
local:
  server:
    port: 9191
app:
  security:
    ignored: /prospect