spring:
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:8889/medical_info
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rsocket:
    server:
      transport: websocket
      mapping-path: /rsocket
local:
  server:
    port: 8080
app:
  security:
    ignored: /prospect